### ISSUE TITLE
Refactor auth service: Update register, login, and add authenticate method

### ISSUE THREAD

**Issue by the-berufegoru** [karma-nest/job-nest#14]
refactor the auth service to incorporate the following changes

1. Register Service

    Remove confirmPassword field: No longer need to verify the password confirmation.
    Response: The response should now return the candidate object.
    Account Verification: Introduce an accountVerification field (defaults to false). If set to true, a verification email will be sent.

2. Login Service

    Remove rememberMe field: No longer include the rememberMe functionality.
    Response: Return a candidate or recruiter payload depending on the user's role.

3. Authenticate Method

    New method: Add a new method to generate and return a JWT token for the user based on their email.

# Tasks

- [ ] Update register.service.ts to reflect the changes in the register service.
- [ ]  Refactor login.service.ts to adjust the login response and remove the rememberMe feature.
- [ ] Create the authenticate method in auth.service.ts to return a JWT token.
- [ ] Update any necessary tests to reflect the changes in the services.
